export class ToonStats {
    constructor(
        public amountToons: number,
        public amountToonsAbove100Laff: number,
        public amountToonsMaxed: number,
        
        public amountCats: number,
        public amountDogs: number,
        public amountMice: number,
        public amountRabbits: number,
        public amountHorses: number,
        public amountPigs: number,
        public amountMonkeys: number,
        public amountBears: number,
        public amountCrocodiles: number,
        public amountDeer: number,
        public amountDucks: number,

        public amountCatsAbove100Laff: number,
        public amountDogsAbove100Laff: number,
        public amountMiceAbove100Laff: number,
        public amountRabbitsAbove100Laff: number,
        public amountHorsesAbove100Laff: number,
        public amountPigsAbove100Laff: number,
        public amountMonkeysAbove100Laff: number,
        public amountBearsAbove100Laff: number,
        public amountCrocodilesAbove100Laff: number,
        public amountDeerAbove100Laff: number,
        public amountDucksAbove100Laff: number,

        public amountCatsMaxed: number,
        public amountDogsMaxed: number,
        public amountMiceMaxed: number,
        public amountRabbitsMaxed: number,
        public amountHorsesMaxed: number,
        public amountPigsMaxed: number,
        public amountMonkeysMaxed: number,
        public amountBearsMaxed: number,
        public amountCrocodilesMaxed: number,
        public amountDeerMaxed: number,
        public amountDucksMaxed: number,

        public amountToonsWithToonUp: number,
        public amountToonsWithTrap: number,
        public amountToonsWithLure: number,
        public amountToonsWithSound: number,
        public amountToonsWithThrow: number,
        public amountToonsWithSquirt: number,
        public amountToonsWithDrop: number,

        public amountToonsWithToonUpAbove100Laff: number,
        public amountToonsWithTrapAbove100Laff: number,
        public amountToonsWithLureAbove100Laff: number,
        public amountToonsWithSoundAbove100Laff: number,
        public amountToonsWithThrowAbove100Laff: number,
        public amountToonsWithSquirtAbove100Laff: number,
        public amountToonsWithDropAbove100Laff: number,

        public amountToonsWithToonUpMaxed: number,
        public amountToonsWithTrapMaxed: number,
        public amountToonsWithLureMaxed: number,
        public amountToonsWithSoundMaxed: number,
        public amountToonsWithThrowMaxed: number,
        public amountToonsWithSquirtMaxed: number,
        public amountToonsWithDropMaxed: number,

        public amountOrganicNone: number,
        public amountOrganicToonUp: number,
        public amountOrganicTrap: number,
        public amountOrganicLure: number,
        public amountOrganicSound: number,
        public amountOrganicThrow: number,
        public amountOrganicSquirt: number,
        public amountOrganicDrop: number,

        public amountTier8Sellbot: number,
        public amountTier8Cashbot: number,
        public amountTier8Lawbot: number,
        public amountTier8Bossbot: number,
    ) {}
}